server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Resolver DNS Kubernetes - résout backend-service dynamiquement
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    # Gère les routes Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend - résolution dynamique à chaque requête
    location /customers {
        set $backend http://backend-service.default.svc.cluster.local:8080;
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}












