---
- name: Playbook_Continous_Deployment
  hosts: DockerSRV
  become: yes
  gather_facts: no

  vars:
    docker_image_frontend: "acmanso/frontend"
    docker_image_backend:  "acmanso/backend"
    docker_image_tag:      "{{ IMAGE_TAG }}"

  tasks:
  
    - name: Pull latest Frontend image
      docker_image:
        name: "{{ docker_image_frontend }}:{{ docker_image_tag }}"
        source: pull

    - name: Pull latest Backend image
      docker_image:
        name: "{{ docker_image_backend }}:{{ docker_image_tag }}"
        source: pull
